FROM python:3.8-slim

RUN apt update && apt install -y \
    gcc \
    g++ \
    make \
    libffi-dev \
    libopenblas-dev \
    && rm -rf /var/lib/apt/lists/*

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
CMD streamlit run app.py
